### ISSUE TITLE
Implement chunking the reference genome

### ISSUE THREAD

**Issue by martinghunt** [iqbal-lab-org/minos#31]
Split the reference approximately every N kilobases.
Don't split inside a variant (ie inside REF string of VCF).
Need to include at least one read length of reference genome flanking each variant, so that quasimap works and can call the variant. This means chunks can overlap.
Run variant calling on each chunk.
When putting back together, for variants that are in >1 chunk, only use the call with the biggest genotype confidence.

**Comment by iqbal-lab** [comment]
adding Robyn on "cc" list so he knows what doing

**Comment by martinghunt** [comment]
Implemented. See pull request #32. Kept track of which variants should be called in each split VCF file. The when merging ignore the calls as required, instead of using max genotype confidence.
