### ISSUE TITLE
Check if whitespace in seq names breaks minos

### ISSUE THREAD

**Issue by martinghunt** [iqbal-lab-org/minos#66]
Check what happens if there is whitespace in fasta headers of input file. It might break the pipeline because names then might not match what is in the VCF file.

**Comment by sjbush** [comment]
I believe it does (I'm using v0.12.2). Tested on a ref fasta with the header:

>NC_004668.1 Enterococcus faecalis V583, complete sequence

I get the error: "Exception: No VCF records. Cannot continue. Please check that the input VCF files contained at least one variant"

But if I change to:

>NC_004668.1

Works fine - and congrats on the paper!

**Comment by martinghunt** [comment]
Thanks! Have fixed it. Try the new release 0.12.3
