### ISSUE TITLE
Filter on depth and gt conf percentile

### ISSUE THREAD

**Issue by martinghunt** [iqbal-lab-org/minos#68]
Filter with default DP>2 and GT_CONF_PERCENTILE >2.5.

**Comment by martinghunt** [comment]
@iqbal-lab there's an issue here with the multi sample pipeline. Adding a filter breaks the test that the final merge-of-all-samples VCF file is "correct". For whatever correct means, seeing as there is >1 sample in the file but only one filter column.

I think we agreed to stop the multi sample pipeline from making the final merged VCF file, because it's usually too big for how the current code works (load everything into memory), and because the filter column doesn't work for >1 sample VCFs?

I can for now disable the check of the final merged VCF file? I don't even know what it should look like.

Other than that, I've got the filter ready to go. All the other tests pass with the filter column implemented.

**Comment by iqbal-lab** [comment]
Awesome, I agree the multi sample pipeline should for now just output one vcf per sample with associated easy handling of FILTER column. Yes for now disable check but also remove the merge is good

**Comment by iqbal-lab** [comment]
oops, cc @martinghunt

**Comment by martinghunt** [comment]
In release 0.6.0
