### ISSUE TITLE
multi-sample pipeline: parallelise (nextflow) chunk building

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/minos#72]
Currently gramtools build of chunks happens in a python loop, possibly with threads if told to do so.

https://github.com/iqbal-lab-org/minos/blob/c9d856c03c9dad3e760d25f6e1ae0c688380c3c1/minos/vcf_chunker.py#L205

this is a massive and unnecessary bottleneck when running on tens of thousands of samples,

This is the build times for the first 600-odd chunks (out of 5000) when running on 50,000 TB genomes. As you can see, the half of the chunks take less than 140 seconds to build. 3 of them take 16 mins (1000sec). 5 of them take over 30 mins.
<img width="537" alt="Screenshot 2019-06-02 at 22 56 01" src="https://user-images.githubusercontent.com/6476513/58767970-3bb24d00-858b-11e9-87d2-2bad68921bdc.png">

**Comment by iqbal-lab** [comment]
At this rate it will take me 2 weeks just to build things, but I'm quite tied up this week. Will talk to @leoisl and @bricoletc to see if they have any spare time

**Comment by bricoletc** [comment]
Nextflow script can now do `build` of each split in parallel.

We could also now seek to parallelise each run of `gramtools quasimap` and `infer`: right now, after build on each split, `minos adjudicate` is run parallelised by sample; quasimap/infer run in single process on all splits

**Comment by iqbal-lab** [comment]
i am happy to live with just build parallelised for now
