### ISSUE TITLE
removing perl_generated_vcf caused a bug

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/minos#76]
ERROR ~ Error executing process > 'minos_all_small_vars (12)'

Caused by:
  Process `minos_all_small_vars (12)` terminated with an error exit status (1)

Command executed:

  sample_name=$(cat sample_name.37)
  minos_outdir=small_vars.minos.37
  minos adjudicate  --sample_name $sample_name --gramtools_build_dir /hps/nobackup/iqbal/zi/Cryptic_releases/nextflow.work/f2/855ff40b18dd238c529b231e1f7d95/gmtools_build_dir --reads /nfs/leia/research/iqbal/mhunt/Cryptic_production/Pipeline_root/00/00/05/27/527/Pipelines/1/variant_call/0.7.3.ref.3/samtools/rmdup.bam $minos_outdir /nfs/leia/research/iqbal/mhunt/Cryptic_production/Pipeline_refs/3/ref.fa "small_vars_clustered.vcf"

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/pyfastaq/utils.py", line 21, in open_file_read
      f = open(filename)
  FileNotFoundError: [Errno 2] No such file or directory: '/hps/nobackup/iqbal/zi/Cryptic_releases/nextflow.work/77/f9b9651dc28b949dfcf91257f014f0/gramtools.build_dir/split.0.gramtools_build/perl_generated_vcf'
  
Work dir:
  /hps/nobackup/iqbal/zi/Cryptic_releases/nextflow.work/27/fc27423b35372a9638fbed7c3b4976

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by iqbal-lab** [comment]
@bricoletc if you have a chance to take a look, i'd appreciate it

**Comment by bricoletc** [comment]
I think https://github.com/iqbal-lab-org/minos/commit/798a7dfd2a95d44ad8c4b9f4076a60db4cf7f566 fixes this.

**Comment by bricoletc** [comment]
Confirm this has been fixed as we successfully ran `minos adjudicate` on 49k Mtb samples
