### ISSUE TITLE
Invalid DP FORMAT header

### ISSUE THREAD

**Issue by mbhall88** [iqbal-lab-org/minos#77]
https://samtools.github.io/hts-specs/VCFv4.2.pdf
FORMAT headers can only have the following keys: ID, Number, Type, and Description.  

I have a depth header from minos (v0.5.1 according to the header) which is the folllowing:
```
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="total kmer depth from gramtools",Source="minos">
```
`Source` keys can only be in INFO fields. So I guess remove it from FORMAT and create an INFO field also for DP? Either way it needs to be removed from the DP FORMAT header

**Comment by bricoletc** [comment]
@martinghunt what do you think about this? what was the rationale for having `Source` in the `DP` FORMAT field?

**Comment by martinghunt** [comment]
@bricoletc The rationale was to have a record that minos was the source of the information.

@mbhall88  Looks like this _is_ valid to me. Was it breaking a tool/parser for you? From the VCF spec v4.2 on page 3:

> For all of the ##INFO, ##FORMAT, ##FILTER, and ##ALT metainformation, extra fields can be included after the default fields. For example:
>
> `##INFO=<ID=ID,Number=number,Type=type,Description="description",Source="description",Version="128">`
>
> In the above example, the extra fields of “Source” and “Version” are provided. Optional fields should be stored as strings even for numeric values.

**Comment by martinghunt** [comment]
Ideally, I'd add `Source="minos",Version="x.y.z"` to all the FILTER and FORMAT lines in the header of the VCF made by minos. But not if it's breaking other tools.

**Comment by martinghunt** [comment]
I've left out the source = foo from the header lines.

**Comment by mbhall88** [comment]
Ah yeah you're right. It was breaking a tool - can't remember which one though. If it is valid as per the specs then keep it in and it is then an issue for the associated breaking tool to fix.
