### ISSUE TITLE
Make unit tests discoverable

### ISSUE THREAD

**Issue by martinghunt** [iqbal-lab-org/minos#80]
@bricoletc  Why not just run the usual `python3 setup.py test`?

**Comment by bricoletc** [comment]
Woops is that what should be done? You're right it works fine- i'd been using python3 -m unittest so far.
What is your way of developing in minos @martinghunt , how do you get gramtools set up?

**Comment by martinghunt** [comment]
Now done using tox/pytest in PR #93
